/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedCertificationIndexRouteImport } from './routes/_authenticated/certification.index'
import { Route as AuthenticatedCertificationLevelNRouteImport } from './routes/_authenticated/certification.$level.$n'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificationIndexRoute =
  AuthenticatedCertificationIndexRouteImport.update({
    id: '/certification/',
    path: '/certification/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificationLevelNRoute =
  AuthenticatedCertificationLevelNRouteImport.update({
    id: '/certification/$level/$n',
    path: '/certification/$level/$n',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/certification/': typeof AuthenticatedCertificationIndexRoute
  '/certification/$level/$n': typeof AuthenticatedCertificationLevelNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/certification': typeof AuthenticatedCertificationIndexRoute
  '/certification/$level/$n': typeof AuthenticatedCertificationLevelNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/certification/': typeof AuthenticatedCertificationIndexRoute
  '/_authenticated/certification/$level/$n': typeof AuthenticatedCertificationLevelNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/journal'
    | '/certification/'
    | '/certification/$level/$n'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/journal' | '/certification' | '/certification/$level/$n'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/journal'
    | '/_authenticated/certification/'
    | '/_authenticated/certification/$level/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certification/': {
      id: '/_authenticated/certification/'
      path: '/certification'
      fullPath: '/certification/'
      preLoaderRoute: typeof AuthenticatedCertificationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certification/$level/$n': {
      id: '/_authenticated/certification/$level/$n'
      path: '/certification/$level/$n'
      fullPath: '/certification/$level/$n'
      preLoaderRoute: typeof AuthenticatedCertificationLevelNRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedCertificationIndexRoute: typeof AuthenticatedCertificationIndexRoute
  AuthenticatedCertificationLevelNRoute: typeof AuthenticatedCertificationLevelNRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedCertificationIndexRoute: AuthenticatedCertificationIndexRoute,
  AuthenticatedCertificationLevelNRoute: AuthenticatedCertificationLevelNRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
